### ISSUE TITLE
colcon build failing on python modules

### ISSUE THREAD

**Issue by zmichaels11** [colcon/colcon-python-setup-py#31]
Version used: 0.24
OS: Ubuntu Bionic x86_64
ROS version: melodic

Steps to reproduce break:
1. install latest colcon from pip
1. create a new workspace
1. clone https://github.com/zmichaels11/test-py-module into workspace
1. run `colcon build`

This works on version 0.23, which can be acquired from apt.

**Comment by zmichaels11** [comment]
Reserving this comment for output of error

**Comment by dirk-thomas** [comment]
Please see #32 for the proposed fix.

**Comment by zmichaels11** [comment]
Testing fix on a clean machine
