### ISSUE TITLE
setuptools warning causing build failure 

### ISSUE THREAD

**Issue by baldonp1** [colcon/colcon-python-setup-py#38]
Hi, sorry if this is not the right place for this issue - I wasn't able to nail down the exact source. Please let me know if it's better suited for a different Colcon or ROS  repo.

Info:
- OS: NVIDIA Jetpack 4.4 (Ubuntu 18.04 derivative)
- Hardware: NVIDIA Jetson Xaiver (dev kit)
- Software: colcon-ros (0.3.18)

After a fresh install of the OS I build ROS2 Eloquent from source and installed it. This also installed a bunch of the colcon packages. I followed the installation steps provided by ROS [here](https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/).

Everything built and worked, including the example from the install guide. However, I got the below error during the `colcon build --symlink-install` step.

Following this, I looked at the [ROS Colcon package tutorial](https://index.ros.org/doc/ros2/Tutorials/Colcon-Tutorial/). During build I got the same error as before, and during test all of the python examples failed due to the error. 

Error:
`"Distutils was imported before Setuptools. This usage is discouraged "
/home/pcadmin/.local/lib/python3.6/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.`

Solution:
I was able to rollback setuptools to v44.1.1 and this resolved the error during build. There's an unrelated error during test - I suspect this is due to the warnings from the ROS2 build. Currently rebuilding ROS2 now that I resolved the warning, will report if the test continues to fail after the rebuild.    

Again, not sure what exactly in the ROS/Colcon setup process installed distutils, or if that's even the exact issue, but I thought I'd post this somewhere in case it helps anyone else... spent a lot of time trying to figure out what was wrong.

Cheers!

**Comment by dirk-thomas** [comment]
Can you post the full output if the build actually *fails* for you due to this warning?

**Comment by baldonp1** [comment]
Great thank you! Sorry I'm a bit of a noob with Colcon and ROS. 

I should've been a little more precise with my wording. The builds never failed, there was only the warnings, no other errors or messages to post. But when I would run `colcon test` all of the Python parts of the example would fail the test and not run. 

I just finished rebuilding ROS after updating my setuputils version, otherwise I'd reproduce and share the full terminal output/build logs. But after the rebuild everything works and runs as expected.

Also, my original setuptools version was v49.2.0.

**Comment by dirk-thomas** [comment]
> But when I would run `colcon test` all of the Python parts of the example would fail the test and not run.

Please share details about this. I don't see why this would fail any tests.

**Comment by baldonp1** [comment]
Ok. Just switched back to v49.2.0 to reproduce. Below is the full output from the colcon build and test. Unfortunately test the output is a bit different than before, but similar enough. When first posting, I was not receiving any ===warnings summary=== sections or warnings about pytest. It only showed the setuptools user warnings, the Finished [with test failures], and the list of python packages that failed. Previously there weren't 'packages with stderr output', it was just the 'packages had test failures' list with every python example. 

This very well could just be me misunderstanding the output, maybe there isn't really a problem. In which case my apologies for wasting your time. But for what it's worth the setuptools version change resolved that warning. 

`colcon build --symlink-install`:

`/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Starting >>> examples_rclcpp_minimal_action_client
Starting >>> examples_rclcpp_minimal_action_server
Starting >>> examples_rclcpp_minimal_client
Starting >>> examples_rclcpp_minimal_composition
Starting >>> examples_rclcpp_minimal_publisher
Starting >>> examples_rclcpp_minimal_service
Starting >>> examples_rclcpp_minimal_subscriber
Starting >>> examples_rclcpp_minimal_timer
Finished <<< examples_rclcpp_minimal_client [2.07s]
Starting >>> examples_rclcpp_multithreaded_executor
Finished <<< examples_rclcpp_minimal_publisher [2.03s]
Finished <<< examples_rclcpp_minimal_action_client [2.40s]
Finished <<< examples_rclcpp_minimal_action_server [2.33s]
Finished <<< examples_rclcpp_minimal_service [2.04s]
Finished <<< examples_rclcpp_minimal_timer [1.93s]
Starting >>> examples_rclpy_executors
Starting >>> examples_rclpy_minimal_action_client
Starting >>> examples_rclpy_minimal_action_server
Starting >>> examples_rclpy_minimal_client
Finished <<< examples_rclcpp_minimal_subscriber [2.40s]
Starting >>> examples_rclpy_minimal_publisher
Starting >>> examples_rclpy_minimal_service
Finished <<< examples_rclcpp_minimal_composition [2.87s]
Starting >>> examples_rclpy_minimal_subscriber
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Finished <<< examples_rclcpp_multithreaded_executor [17.0s]
Finished <<< examples_rclpy_executors [19.3s]                             
Finished <<< examples_rclpy_minimal_action_server [19.2s]
Finished <<< examples_rclpy_minimal_action_client [19.3s]
Finished <<< examples_rclpy_minimal_client [19.2s]
Finished <<< examples_rclpy_minimal_publisher [19.1s]
Finished <<< examples_rclpy_minimal_subscriber [18.9s]
Finished <<< examples_rclpy_minimal_service [19.1s]

Summary: 16 packages finished [22.8s]`

`colcon test`:

`/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Starting >>> examples_rclcpp_minimal_action_client
Starting >>> examples_rclcpp_minimal_action_server                   
Starting >>> examples_rclcpp_minimal_client
Starting >>> examples_rclcpp_minimal_composition
Starting >>> examples_rclcpp_minimal_publisher
Starting >>> examples_rclcpp_minimal_service
Starting >>> examples_rclcpp_minimal_subscriber
Starting >>> examples_rclcpp_minimal_timer
Finished <<< examples_rclcpp_minimal_action_client [0.76s]
Finished <<< examples_rclcpp_minimal_action_server [0.67s]
Finished <<< examples_rclcpp_minimal_client [0.61s]
Finished <<< examples_rclcpp_minimal_composition [0.52s]
Starting >>> examples_rclcpp_multithreaded_executor
Starting >>> examples_rclpy_executors 
Starting >>> examples_rclpy_minimal_action_client
Starting >>> examples_rclpy_minimal_action_server
Finished <<< examples_rclcpp_minimal_publisher [0.76s]
Starting >>> examples_rclpy_minimal_client
Finished <<< examples_rclcpp_minimal_service [0.77s]
Starting >>> examples_rclpy_minimal_publisher
Finished <<< examples_rclcpp_minimal_subscriber [0.77s]
Finished <<< examples_rclcpp_minimal_timer [0.70s]
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Starting >>> examples_rclpy_minimal_service
Starting >>> examples_rclpy_minimal_subscriber
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Finished <<< examples_rclcpp_multithreaded_executor [11.6s]
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/usr/local/lib/python3.6/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
--- stderr: examples_rclpy_minimal_action_client                          
=============================== warnings summary ===============================
/home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417
  /home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113: PytestDeprecationWarning: direct construction of Package has been deprecated, please use Package.from_parent
    return pytest.Package(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---
Finished <<< examples_rclpy_minimal_action_client [15.8s]
--- stderr: examples_rclpy_executors
=============================== warnings summary ===============================
/home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417
  /home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113: PytestDeprecationWarning: direct construction of Package has been deprecated, please use Package.from_parent
    return pytest.Package(path, parent)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114: PytestDeprecationWarning: direct construction of Module has been deprecated, please use Module.from_parent
    return pytest.Module(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---
Finished <<< examples_rclpy_executors [15.9s]	[ with test failures ]
--- stderr: examples_rclpy_minimal_action_server
=============================== warnings summary ===============================
/home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417
  /home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113: PytestDeprecationWarning: direct construction of Package has been deprecated, please use Package.from_parent
    return pytest.Package(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---
Finished <<< examples_rclpy_minimal_action_server [15.7s]
--- stderr: examples_rclpy_minimal_client
=============================== warnings summary ===============================
/home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417
  /home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113: PytestDeprecationWarning: direct construction of Package has been deprecated, please use Package.from_parent
    return pytest.Package(path, parent)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114: PytestDeprecationWarning: direct construction of Module has been deprecated, please use Module.from_parent
    return pytest.Module(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---
Finished <<< examples_rclpy_minimal_client [15.7s]	[ with test failures ]
--- stderr: examples_rclpy_minimal_publisher
=============================== warnings summary ===============================
/home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417
  /home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113: PytestDeprecationWarning: direct construction of Package has been deprecated, please use Package.from_parent
    return pytest.Package(path, parent)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114: PytestDeprecationWarning: direct construction of Module has been deprecated, please use Module.from_parent
    return pytest.Module(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---
Finished <<< examples_rclpy_minimal_publisher [15.8s]	[ with test failures ]
--- stderr: examples_rclpy_minimal_service
=============================== warnings summary ===============================
/home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417
  /home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113: PytestDeprecationWarning: direct construction of Package has been deprecated, please use Package.from_parent
    return pytest.Package(path, parent)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114: PytestDeprecationWarning: direct construction of Module has been deprecated, please use Module.from_parent
    return pytest.Module(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---
Finished <<< examples_rclpy_minimal_service [13.6s]	[ with test failures ]
--- stderr: examples_rclpy_minimal_subscriber                       
=============================== warnings summary ===============================
/home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417
  /home/pcadmin/.local/lib/python3.6/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:113: PytestDeprecationWarning: direct construction of Package has been deprecated, please use Package.from_parent
    return pytest.Package(path, parent)

/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
/home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114
  /home/pcadmin/ros2_eloquent/build/launch_testing/launch_testing/pytest/hooks.py:114: PytestDeprecationWarning: direct construction of Module has been deprecated, please use Module.from_parent
    return pytest.Module(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---
Finished <<< examples_rclpy_minimal_subscriber [15.6s]	[ with test failures ]

Summary: 16 packages finished [22.3s]
  7 packages had stderr output: examples_rclpy_executors examples_rclpy_minimal_action_client examples_rclpy_minimal_action_server examples_rclpy_minimal_client examples_rclpy_minimal_publisher examples_rclpy_minimal_service examples_rclpy_minimal_subscriber
  5 packages had test failures: examples_rclpy_executors examples_rclpy_minimal_client examples_rclpy_minimal_publisher examples_rclpy_minimal_service examples_rclpy_minimal_subscriber`

**Comment by dirk-thomas** [comment]
Since several packages passed without test failures I would guess this has nothing to do with the setuptools warning. You can look into what actual tests failed and why with: `colcon test-result --verbose`.

**Comment by baldonp1** [comment]
You're likely correct. I'll look into that. I'm going to close this out since the warning is resolved, and the other issues are unrelated. Thanks for the help!

**Comment by dirk-thomas** [comment]
I will keep this ticket open until the two referenced PRs have been merged which avoid the warning when `setuptools` 49.2.0 is used.

**Comment by baldonp1** [comment]
Whoops, sorry!
