### ISSUE TITLE
setuptools 72.2.0 breaks colcon-python-setup-py

### ISSUE THREAD

**Issue by lianghongzhuo** [colcon/colcon-python-setup-py#58]
similar to https://github.com/colcon/colcon-python-setup-py/issues/56
but this time, setuptools removes: setuptools.extern.packaging
and I get error: `ModuleNotFoundError: No module named 'setuptools.extern.packaging'`

I fixed it by running: ` pip  install setuptools=70.1.1`

**Comment by lianghongzhuo** [comment]
the wrong import still in master branch: https://github.com/colcon/colcon-python-setup-py/blob/master/colcon_python_setup_py/package_identification/python_setup_py.py#L253

**Comment by lianghongzhuo** [comment]
any updates?

**Comment by homalozoa** [comment]
Just remove 'setuptools.extern.' on line 251, if the version of your colcon-python-setup-py is 0.2.7. See https://github.com/colcon/colcon-python-setup-py/pull/44/files for more details. @lianghongzhuo

**Comment by lianghongzhuo** [comment]
True, this have been fixed in master
